name: youphoria
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^1.24.0
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_core_platform_interface: ^4.5.1 #new FIXES EVERYTHING ðŸ”¥ (no carrot)
  firebase_auth_platform_interface: ^6.1.10
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  rive: ^0.10.3
  rxdart: 0.27.4
  json_annotation: ^4.5.0
  animations: ^2.0.7
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: CuteDropCaps
      fonts:
        - asset: fonts/CuteDrop-Caps.otf
          weight: 700
  assets:
    - assets/images/
    - assets/animations/
    - .env
